### ISSUE TITLE
tcl.m4 is very old

### ISSUE THREAD

**Issue by ComputerJock** [auriocus/tksvg#1]
I've built tksvg on Win7x64 using Msys2 64-bit. It is working fine -- thank you!

I had to use a much more recent version of tcl.m4 and re-run autoconf

I used this one: tcl8.6.6/pkgs/thread2.8.0/tclconfig/tcl.m4

I copied the replacement tcl.m4 to tclconfig/ and reran 'autoconf'

Running this configure now works fine:

$ PATH="/C/progra~1/tcl/bin:$PATH" ./configure \
    --with-tcl=/c/progra~1/tcl/lib \
    --with-tk=/c/progra~1/tcl/lib \
    --enable-64bit \
    --exec-prefix=`pwd`/PREFIX

A "make" builds the library correctly for windows 64-bit

The only problem is the "make install" which results in:

$ make install
 /bin/sh ./tclconfig/install-sh -c @INSTALL_FLAGS@ tksvg01.dll /C/Users/me/Downloads/tcl/TkSvg/tksvg-master/PREFIX/lib/tksvg0.1/tksvg01.dll
cp: cannot stat '@INSTALL_FLAGS@': No such file or directory
mv: cannot stat '/C/Users/me/Downloads/tcl/TkSvg/tksvg-master/PREFIX/lib/tksvg0.1/#inst.5552#': No such file or directory
 : /C/Users/me/Downloads/tcl/TkSvg/tksvg-master/PREFIX/lib/tksvg0.1/tksvg01.dll
 Install pkgIndex.tcl /C/Users/me/Downloads/tcl/TkSvg/tksvg-master/PREFIX/lib/tksvg0.1
Installing header files in /mingw64/include

I don't know enough about autoconf etc. to remove the reference to @INSTALL_FLAGS@. I can easily work around it by either editing the Makefile or copying the DLL manually.

**Comment by auriocus** [comment]
INSTALL_FLAGS was set by the old tcl.m4 to "-s". Not sure what that really does, I think it strips the debug symbols. I will update tcl.m4, as you suggest, and also get a newer copy of Makefile.in

**Comment by auriocus** [comment]
tclconfig was updated to the most recent version
