### ISSUE TITLE
crash when <style> present

### ISSUE THREAD

**Issue by bll123** [auriocus/tksvg#10]
This image causes a crash:

https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/circles1.svg

References: 

https://groups.google.com/d/msg/comp.lang.tcl/FLr0h3fjlxg/bIhydHsCCAAJ

https://groups.google.com/d/msg/comp.lang.tcl/FLr0h3fjlxg/lIJmym-FCAAJ

**Comment by fvogelnew1** [comment]
Crash can be reproduced by:


package require Tk

set data {<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg">
  <style type="text/css">
    circle:hover {fill-opacity:0.9;}
  </style>
  <g style="fill-opacity:0.7;">
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:red; stroke:black; stroke-width:0.1cm" transform="translate(0,50)"/>
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:blue; stroke:black; stroke-width:0.1cm" transform="translate(70,150)"/>
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:green; stroke:black; stroke-width:0.1cm" transform="translate(-70,150)"/>
  </g>
</svg>}

image create photo foo -data $data

**Comment by oehhar** [comment]
Thank you for reporting this.

I was today able to reproduce the crash with MS-VC2015 32 bit.
As written before, the issue does not arise with MS-VC6++ compiled tksvg0.3 and all works as expected.

The command line in the VC2015 x86 native tools prompt was:

`nmake -f makefile.vc TCLDIR=c:\test\tcl8.6.9_vs2015_symbols OPTS=symbols TKDIR=c:\test\tk8.6.9_vs2015_symbols
`

The error arises in an internal program of windows dealing with heaps (debug_heap.cpp).
I will try the next week to find out more.

**Comment by oehhar** [comment]
The crash happens in function: nsvg__deleteStyles in the command "free(style->name);".
style->name has the value "circle:hover". That looks all o.k. so far.

The issue was that style->name was malleced by NANOSVG_malloc but freed by "free".
When a different heap-function was used for NANOSVG_malloc, the pointer was invalid for free.

A pull request to fix is was probably issued.

**Comment by auriocus** [comment]
Fixed
