### ISSUE TITLE
windows: msys2: 32-bit gcc 10.1.0

### ISSUE THREAD

**Issue by bll123** [auriocus/tksvg#12]
This new compiler version is causing me issues.
It appears that images created with tksvg using gcc 10.1.0 are not working right.
It crashes when the image is put to use.
64-bit, same version of the compiler works fine.

**Comment by oehhar** [comment]
Brad,
thank you for the message. Are you sure you have used the version in trunk ?
The released 0.3 version suffers from a memory free bug on some systems.

See ticket # 10:
https://github.com/auriocus/tksvg/issues/10

This fix is also included in tk8.7a3.

Or do you see another issue ?

Thank you,
Harald

**Comment by bll123** [comment]
I believe I am using 0.3. (I don't use hover, don't think that bug affects me).

But the problem didn't show up during the use of tksvg, but afterwards when I 
tried to use the images.   So I don't know if I will be able to find anything.

My 8.6.10, which built properly before, no longer builds properly using this newish release of
mingw-gcc 32-bit 10.1.0.    And the exact same code works with the 64-bit version
of the compiler.    I solved the build issues I had, but now this tksvg issue has arisen.

It's late here, but tomorrow I will try and create a small test.
Maybe compile tksvg with all the compiler warning flags turned on and look for any issues.

**Comment by oehhar** [comment]
Good luck, Brad, and good night,
Harald

**Comment by bll123** [comment]
Ok, not an svg problem.  It's a problem with any type of image.
