### ISSUE TITLE
Extended check for correct parsing.

### ISSUE THREAD

**Issue by PaulObermeier** [auriocus/tksvg#2]
When loading tksvg package, "image put" statements do not work correctly anymore.
That's because the parser does not check, if the SVG image could be read correctly.
See following test script (disable **package require tksvg** to see how it should look):

package require Tk
package require tksvg

proc CreateCellImg { color } {
    set img [image create photo -height 13 -width 13]
    $img put $color -to 0 0 13 13
    return $img
}

for { set i 1 } { $i < 10 } { incr i } {
    set colorHex [format "#%02X%02X%02X" [expr $i*20] [expr $i*10] [expr $i*10]]
    label .l_$i -image [CreateCellImg $colorHex]
    pack .l_$i
}

Possible solution:
Add following code at the end of function ParseSVGWithOptions:

    if (nsvgImage == NULL) {
        Tcl_SetResult(interp, "cannot parse SVG image", TCL_STATIC);
        Tcl_SetErrorCode(interp, "TK", "IMAGE", "SVG", "PARSE_ERROR", NULL);
        goto error;
    }
    if (nsvgImage->width == 0.0 && nsvgImage->height == 0.0) {
        Tcl_SetResult(interp, "cannot parse SVG image", TCL_STATIC);
       Tcl_SetErrorCode(interp, "TK", "IMAGE", "SVG", "PARSE_ERROR", NULL);
       goto error;
    }

**Comment by auriocus** [comment]
Fixed with the most recent version
