### ISSUE TITLE
compilation warnings

### ISSUE THREAD

**Issue by bll123** [auriocus/tksvg#6]
Linux:  ubuntu 16.04 64-bit, gcc 5.4.0

./generic/tkImgSVG.c: In function ‘ParseSVGWithOptions’:
./generic/tkImgSVG.c:426:2: warning: enumeration value ‘OPT_DPI’ not handled in switch [-Wswitch]
  switch ((enum fmtOptions) optIndex) {
  ^

**Comment by auriocus** [comment]
Fixed with pull request #7
