### ISSUE TITLE
windows: build issues with msys 

### ISSUE THREAD

**Issue by bll123** [auriocus/tksvg#8]
a) SHLIB_LD is not set, should be the same as ${CC}

b) SHLIB_CFLAGS is not set to -shared

c) SHLIB_LDFLAGS is missing -shared

**Comment by auriocus** [comment]
When building with the windows Makefiles or with configure?
How a where should it be set?

**Comment by bll123** [comment]
Using configure.
Actually, fixing ticket #1 and regenerating the configure script will probably fix this.
Should have realized this was a duplicate.

**Comment by auriocus** [comment]
#1 is fixed, can you test the build again?

**Comment by bll123** [comment]
Looks good.  Fixed.
